# Generated by Django 6.0.2 on 2026-02-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_comment_comment_text_alter_blog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(default='published', max_length=20),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
